/**
 * Single icon entry point for PokéApp.
 * Components import semantic names from here, while Phosphor remains the only
 * general-purpose icon implementation. Pokémon/type-specific marks stay apart.
 */
export {
  Warning as AlertTriangle,
  Warning,
  Orange as Apple,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight as MoveUpRight,
  BookOpen,
  BookBookmark as BookMarked,
  Calendar as CalendarDays,
  CaretDown as ChevronDownIcon,
  CaretRight as ChevronRight,
  Check,
  Circle,
  Target as CircleDot,
  Compass,
  Dna,
  DotsThree as Ellipsis,
  Eye,
  Flag,
  Funnel as Filter,
  GameController as Gamepad2,
  Gauge,
  Scales as GitCompare,
  GridNine as Grid3X3,
  Heart,
  Info,
  SquaresFour as LayoutGrid,
  Books as Library,
  Lightbulb,
  ListBullets as List,
  MapTrifold as Map,
  MapPin,
  ArrowsOutCardinal as Move,
  Package as PackageOpen,
  PenNib as PenTool,
  Plus,
  ArrowClockwise as RefreshCw,
  FloppyDisk as Save,
  MagnifyingGlass as Search,
  GearSix as Settings,
  Shapes,
  Shield,
  ShieldCheck,
  ShieldWarning as ShieldAlert,
  Skull,
  Sparkle as Sparkles,
  Table as TableProperties,
  Tag as Tags,
  Users,
  WifiSlash as WifiOff,
  X,
  X as XIcon,
} from '@phosphor-icons/react'

export type { Icon as PhosphorIcon } from '@phosphor-icons/react'
