/**
 * Single icon entry point for PokéApp.
 * Components import semantic names from here, while Phosphor remains the only
 * general-purpose icon implementation. Pokémon/type-specific marks stay apart.
 */
export {
  Warning as AlertTriangle,
  Warning,
  Orange as Apple,
  ArrowLeft,
  ArrowDown,
  ArrowRight,
  ArrowUpRight as MoveUpRight,
  BookOpen,
  BookBookmark as BookMarked,
  Brain,
  Bug,
  Calendar as CalendarDays,
  CaretDown as ChevronDownIcon,
  CaretUp as ChevronUpIcon,
  CaretRight as ChevronRight,
  Check,
  CheckCircle,
  Circle,
  CircleNotch as LoaderCircle,
  ClockCounterClockwise as History,
  Target as CircleDot,
  Compass,
  Drop,
  Feather,
  Flask,
  Dna,
  DotsThree as Ellipsis,
  Eye,
  Flag,
  Flame,
  Funnel as Filter,
  GameController as Gamepad2,
  Gauge,
  Scales as GitCompare,
  GridNine as Grid3X3,
  Ghost,
  Hexagon,
  Heart,
  Info,
  SquaresFour as LayoutGrid,
  Books as Library,
  Lightbulb,
  Keyboard,
  Leaf,
  Lightning,
  ListBullets as List,
  MapTrifold as Map,
  MapPin,
  Mountains,
  Moon,
  ArrowsOutCardinal as Move,
  Package as PackageOpen,
  PencilSimple as Pencil,
  PenNib as PenTool,
  Play,
  Plus,
  Question,
  ArrowClockwise as RefreshCw,
  FloppyDisk as Save,
  MagnifyingGlass as Search,
  GearSix as Settings,
  Shapes,
  Shield,
  ShieldCheck,
  ShieldWarning as ShieldAlert,
  Snowflake,
  Skull,
  Sparkle as Sparkles,
  Sword,
  Table as TableProperties,
  Tag as Tags,
  Trophy,
  Users,
  WifiSlash as WifiOff,
  X,
  XCircle,
  X as XIcon,
} from '@phosphor-icons/react'

export type { Icon as PhosphorIcon } from '@phosphor-icons/react'
